# 데이터와 행렬

## 선형대수(linear algebra)

선형대수는 데이터 분석에 필요한 각종 계산을 돕는 학문
- 데이터 분석을 할 때는 수많은 숫자로 이루어진 데이터를 다뤄야 함
- 선형대수를 사용하면 대량의 데이터를 포함하는 복잡한 계산 과정을 간단한 수식으로 서술 가능
- 데이터를 다루는 과정을 정확하고 간단하게 서술 가능

## 데이터의 유형 있는 것

선형대수에서 다루는 데이터는 개수나 형태에 따라 크게 네 가지로 나뉜다.
- 스칼라(scalar) : 숫자 하나로 이루어진 데이터
- 벡터(vector) : 여러 숫자로 이루어진 데이터 레코드(data record)
- 행렬(matrix) : 벡터(데이터 레코드)가 여럿인 데이터 집합
- 텐서(tensor) : 같은 크기의 행렬이 여러개 있는 것

## 1. 스칼라(Scalar)

- 하나의 숫자만으로 이루어진 데이터
- 하나의 표본에 대해 조사 및 수집한 데이터가 한 개
  - 데이터의 표본 = 데이터의 대상(target)
  - ex. 1명의 키를 수집
- 0차원 데이터
  - 데이터에서 차원이라는 개념은 데이터의 진행방향을 의미한다.
  - 스칼라는 하나의 데이터만 가지기 때문에 진행방향이 없어 0차원이다.
- $x$와 같이 알파벳 소문자로 표기
- 실수(real number)인 숫자 중의 하나로 실수 집합 $\mathbf{R}$의 원소

## 2. 벡터(Vector)


- 여러 개의 숫자가 특정한 순서대로 모여 있는 것
- 대부분의 데이터 레코드는 여러 개의 숫자로 이루어진 경우가 많음
- 여러 개의 데이터의 묶음
- 1차원 데이터
  - 데이터에서 차원이라는 개념은 데이터의 진행방향을 의미한다.
  - 벡터는 데이터가 열 혹은 행의 한 방향으로 는체로 표현한다.
  - ```python
    array([[5.1],
           [3.5],
           [1.4],
           [0.2]])
    ```
  - 넘파이는 1차원 배열 객체도 대부분 벡터로 인정한다. 이때는 벡터가 마치 하나의 행처럼 표시되어도 실제로는 열이라는 점에 주의한다.
  - ```python
    array([5.1, 3.5, 1.4, 0.2])
    ```
- 벡터 데이터를 처리하는 프로그램에 따라 열 표기를 정확하게 요구하는 경우도 있으니 주의
  - 사이킷런(Scikit-Learn)에서 벡터를 요구하는 경우 반드시 열의 개수가 1개인 2차원 배열 객체를 넣어야 함

- 벡터는 파이썬 Pandas의 Series에 해당하는 개념이다.

- 벡터는 파이썬 Numpy에서 열의 개수가 1개인 2차원 배열(array) 객체로 표현한다.

In [7]:
import numpy as np

a = np.array([[5.1],[3.5],[1.4],[0.2]]) 
a

array([[5.1],
       [3.5],
       [1.4],
       [0.2]])

- 넘파이는 1차원 배열 객체도 대부분 벡터로 인정한다. 이때는 벡터가 마치 하나의 행처럼 표시되어도 실제로는 열이라는 점에 주의한다.

In [9]:
b = np.array([5.1, 3.5, 1.4, 0.2])
b

array([5.1, 3.5, 1.4, 0.2])

- 벡터 데이터를 처리하는 프로그램에 따라 열 표기를 정확하게 요구하는 경우도 있으니 주의
  - 사이킷런(Scikit-Learn)에서 벡터를 요구하는 경우 반드시 열의 개수가 1개인 2차원 배열 객체를 넣어야 함

### 2-1. 열 벡터(Column Vector)
- $N$개의 행(row), 1개의 열(column)을 가지는 형태
- 일반적으로 벡터는 열 벡터를 의미한다.
- 벡터의 원소를 위에서 아래로 내려써서 표기

$$ x = \begin{bmatrix}x_{1} \\x_{2} \\\vdots \\x_{N} \\\end{bmatrix}  $$

- $N$개의 표본에 대한 한 가지 종류의 데이터 묶음
  - ex. 3명에 대한 키를 수집

### 2-2. 행 벡터(Row Vector)
- 1개의 행(row), $N$개의 열(column)을 가지는 형태

$$ x^T = \begin{bmatrix}x_{1}, x_{2}, \dots, x_{N} \end{bmatrix} $$

- 열 벡터를 전치 연산한 것이 행 벡터
  - 전치(Transpose) 연산 : 행과 열을 바꾸는 연산
  - $x^T$는 벡터 $x$에 전치(Transpose) 연산을 적용했다는 뜻

- 1개의 표본에 대한 $N$ 가지 종류의 데이터 묶음
  - ex. 1명에 대한 키, 몸무게, 나이를 수집

### n-차원 벡터(n-dimensional vector)
하나의 벡터를 이루는 데이터 개수가 $n$일 때 해당 벡터를 n-차원 벡터(n-dimensional vector)라고 하며 다음처럼 표기한다.

$$
x = \begin{bmatrix}
x_{1} \\
x_{2} \\
\vdots \\
x_{N} \\
\end{bmatrix}
$$

$$ x \in \mathbf{R}^N $$

### 특징 벡터(feature vector)
데이터 벡터가 특정한 예측 문제에서 입력 데이터로 사용되면 특징 벡터라고 한다.

### 벡터 기호 표기
- 벡터와 스칼라를 구분하기 위해 벡터 기호로 볼드체 벡터 기호 $\mathbf{x}$나 화살표 벡터 기호 $\vec{x}$를 사용하기도 한다.
  - 하지만 모든 값이 벡터나 행렬이므로 굳이 해당 기호를 사용하지 않을 수 있다. 문맥상 스칼라인지 벡터인지 결정해야 한다.

$$
\mathbf{x} = \vec{x} =
\begin{bmatrix}
x_{1} \\
x_{2} \\
\vdots \\
x_{N} \\
\end{bmatrix}
$$

## 3. 행렬(Matrix)

복수의 차원을 가지는 데이터 레코드가 다시 여러 개 있는 경우의 데이터를 합쳐서 표기한 것

$$
X = 
\begin{bmatrix}
{\begin{matrix} x_{1, 1} & x_{1, 2} & \ldots & x_{1, M}\end{matrix}}  \\
\begin{matrix} x_{2, 1} & x_{2, 2} & \ldots & x_{2, M}\end{matrix} \\
\begin{matrix} \vdots \end{matrix} \\
\begin{matrix} x_{N, 1} & x_{N, 2} & \ldots & x_{N, M}\end{matrix} \\
\end{bmatrix}
$$

$$
X \in \mathbf{R}^{N \times M}
$$

- $N$개의 행(row), $M$개의 컬럼(column)을 가지는 형태
- 복수의 데이터 레코드 집합을 행렬로 나타낼 때 하나의 데이터 레코드가 하나의 행(row)으로 표기한다.
  - 하나의 데이터 레코드를 단독으로 벡터로 나타낼때는 하나의 열로 나타낸다.
  - 이는 데이터 분석에서 쓰는 일반적인 관례이기 때문
- $N$개의 표본(타겟)에 대한 $M$가지 데이터
  - ex. 3명에 대해 키, 몸무게, 나이를 수집

- 행렬은 $X$와 같이 알파벳 대문자로 표기
- 행렬의 원소는 $x_{2,3}$와 같이 두개의 숫자 쌍을 아래첨자로 붙여서 표기
  - 첫 번째 숫자 $2$는 행을 의미
  - 두 번째 숫자 $3$은 열을 의미
  - 행과 열의 개수가 10보다 적을 때 쉼표 없이 $x_{23}$라고 표기할 수 있다.
- 2차원 데이터
  - 데이터의 진행 방향이 행과 열 각각 두 개

- 파이썬 Pandas의 DataFrame에 해당하는 내용

- 파이썬 Numpy에서 행렬을 표기할 때 2차원 `ndarray` 객체를 사용한다.

In [10]:
c = np.array([[11,12,13],[21,22,23]])
c

array([[11, 12, 13],
       [21, 22, 23]])

- 머신러닝은 행렬에 대한 데이터를 다룬다.
- 행렬로 스칼라, 벡터 표현 가능 
  - 스칼라와 벡터도 수학적으로는 행렬에 속한다. 
  - 스칼라는 1개의 행, 1개의 열을 가진 행렬로 볼 수 있다.
    - $$ a \in \mathbf{R}^{1\times 1}  $$
  - 벡터는 N개의 행, 1개의 열을 가진 행렬로 볼 수 있다.
    - $$ x \in \mathbf{R}^{4\times 1}  $$
  - 머신러닝에서 스칼라와 벡터 데이터를 사용해야 할 때 행렬로서 데이터를 표현하여 접근해야 한다.

- 특징행렬
  - 행렬 데이터를 특정 예측 문제를 풀 때 입력 데이터로 사용하면 해당 행을 특징 행렬이라고 한다.
  - 특징 행렬의 크기는 '행의 크기 $\times$ 열의 크기'로 나타낸다.

## 4. 텐서(Tensor)

같은 크기의 행렬이 여러 개 같이 묶여 있는 것
- 3차원 이상의 다차원 데이터
  - 데이터 사이언스 분야에서는 흔히 다차원 배열을 텐서라고 부른다.
  - 참고) 엄격한 수학적 정의로는 텐서는 다차원 배열 자체를 뜻하지 않는다.
- Rank라는 개념과 관련(딥러닝때 다시 말하기로..)

- 머신러닝에서 다루는 데이터는 매트릭스
- 딥러닝에서 다루는 텐서
- 대표적으로 이미지, 영상의 픽셀(pixel)은 RGB에 해당하는 세 가지의 행렬의 묶음, 즉 텐서이다.
- 행렬과 마찬가지로 텐서로 스칼라, 벡터, 행렬 데이터의 표현이 가능하다.

## 전치 연산(Transpose Operation)

- 전치연산은 행렬의 행과 열을 바꾸는 연산
  - 연산 : 데이터를 변형시키는 방법
- 전치 연산은 벡터나 행렬에 $T$라는 위첨자(superscript)를 붙여서 표기
  - $T$는 Transpos를 의미
  - 위첨자로 $T$는 대신 프라임(prime)기호 $'$를 붙이는 경우도 있다.

$$
x \;\; \rightarrow \;\; x^T
$$

$$
x_i,_j \rightarrow  x_j,_i
$$

- $i$는 행 번호, $j$는 열 번호를 의미

- $N\times M$ 차원의 행렬을 전치 연산하면 $M\times N$ 차원의 행렬이 된다.

$$
X = 
\begin{bmatrix}
\boxed{\begin{matrix} x_{1, 1} & x_{1, 2} & x_{1, 3} & x_{1, 4}\end{matrix}}  \\
\begin{matrix} x_{2, 1} & x_{2, 2} & x_{2, 3} & x_{2, 4}\end{matrix} \\
\begin{matrix} x_{3, 1} & x_{3, 2} & x_{3, 3} & x_{3, 4}\end{matrix} \\
\begin{matrix} x_{4, 1} & x_{4, 2} & x_{4, 3} & x_{4, 4}\end{matrix} \\
\begin{matrix} x_{5, 1} & x_{5, 2} & x_{5, 3} & x_{5, 4}\end{matrix} \\
\begin{matrix} x_{6, 1} & x_{6, 2} & x_{6, 3} & x_{6, 4}\end{matrix} \\
\end{bmatrix}
\;\; \rightarrow \;\;
X^T = 
\begin{bmatrix}
\boxed{\begin{matrix} x_{1, 1} \\ x_{1, 2} \\ x_{1, 3} \\ x_{1, 4}\end{matrix}} &
\begin{matrix} x_{2, 1} \\ x_{2, 2} \\ x_{2, 3} \\ x_{2, 4}\end{matrix} &
\begin{matrix} x_{3, 1} \\ x_{3, 2} \\ x_{3, 3} \\ x_{3, 4}\end{matrix} &
\begin{matrix} x_{4, 1} \\ x_{4, 2} \\ x_{4, 3} \\ x_{4, 4}\end{matrix} &
\begin{matrix} x_{5, 1} \\ x_{5, 2} \\ x_{5, 3} \\ x_{5, 4}\end{matrix} &
\begin{matrix} x_{6, 1} \\ x_{6, 2} \\ x_{6, 3} \\ x_{6, 4}\end{matrix} &
\end{bmatrix}
$$

- 전치 연산을 해도 $i=j$인 데이터는 원래 위치 그대로 있는다.
  - $i=j$인 데이터는 주대각 방향에 있다고 표현한다.
  - 전치 연산은 주대각 방향을 기준으로 나머지 데이터를 뒤집는 결과가 나타난다.

### 벡터의 전치 과정
벡터에 전치연산을 적용하려면 벡터를 행렬로 표현해야 한다.

- (열)벡터 $x$에 대해 전치 연산을 적용하여 만든 $x^T$는 **행 벡터(row vector)**

$$ x \in \mathbf{R}^{N\times 1} \rightarrow x^T \in \mathbf{R}^{1\times N} $$

$$ x \in \mathbf{R}^{1\times N} \rightarrow x^T \in \mathbf{R}^{N\times 1} $$


## 특수한 벡터와 행렬

### 영벡터(zeros-vector)
모든 원소가 0인 $N$차원 벡터
  - N개의 행, 1개의 열을 가짐

$$ 
\mathbf{0}_N = \mathbf{0} = 0 =
\begin{bmatrix}
0 \\
0 \\
\vdots \\
0 \\
\end{bmatrix}
$$

$$ 
\begin{align}
0 \in \mathbf{R}^{N \times 1} 
\tag{2.1.28}
\end{align}
$$

### 일벡터(ones-vector)
모든 원소가 1인 $N$차원 벡터

$$ 
\mathbf{1}_N = \mathbf{1}  = 1 = 
\begin{bmatrix}
1 \\
1 \\
\vdots \\
1 \\
\end{bmatrix}
$$

$$ 
1 \in \mathbf{R}^{N \times 1} 
\tag{2.1.30}
$$

### 정방행렬(square matrix)
행의 개수와 열의 개수가 같은 행렬

$$ 
\begin{align}
X = 
\begin{bmatrix}
x_{11} & x_{12} & \cdots & x_{1N} \\
x_{21} & x_{22} & \cdots & x_{2N} \\
\vdots & \vdots & \ddots & \vdots \\
x_{N1} & x_{N12} & \cdots & x_{NN} \\
\end{bmatrix}
\tag{2.1.31}
\end{align}
$$

$$ 
\begin{align}
X \in \mathbf{R}^{N \times N} 
\tag{2.1.32}
\end{align}
$$

### 대각행렬(diagonal matrix)
모든 비대각 요소가 0인 행렬
* 주 대각(main diagonal) : 행렬에서 행과 열이 같은 위치
  - 주대각을 대각이라고도 한다.
* 비대각비대각(off-diagonal) : 주대각 위치에 있지 않은 것들

$$ 
D = 
\begin{bmatrix}
d_{1} & 0 & \cdots & 0 \\
0 & d_{2} & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & d_{M} \\
0 & 0 & \cdots & 0 \\
0 & 0 & \cdots & 0 \\
0 & 0 & \cdots & 0 \\
\end{bmatrix}
$$

$$
D \in \mathbf{R}^{N \times M} 
$$

- 반드시 정방행렬일 필요 없다.

### 항등행렬
대각행렬 중에서도 모든 대각성분의 값이 1인 대각행렬
- 항등행렬은 보통 알파벳 대문자 $I$로 표기

$$ 
I = 
\begin{bmatrix}
1 & 0 & \cdots & 0 \\
0 & 1 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & 1 \\
\end{bmatrix}
$$

$$ 
I \in \mathbf{R}^{N \times N}
$$

### 대칭행렬
전치연산을 통해서 얻은 전치행렬이 원래의 행렬과 같은 행렬
- 정방행렬만 대칭행렬이 될 수 있음

$$ 
S^{T} = S 
$$ 

$$ 
S \in \mathbf{R}^{N \times N} 
$$